# Generated by Django 3.2.8 on 2021-11-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wilaya',
            name='price',
        ),
        migrations.AddField(
            model_name='wilaya',
            name='home_delivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de Livraison'),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='relai_delivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de Livraison'),
        ),
    ]
