# Generated by Django 3.2.8 on 2021-11-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20211101_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wilaya',
            name='home_delivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Livraison à domicile'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='relai_delivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Livraison point de Relais'),
        ),
    ]
