# Generated by Django 3.2.8 on 2021-10-30 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.producttype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Référence'),
        ),
    ]
