# Generated by Django 3.2.8 on 2021-10-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_atributesvalue_specification_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributesvalue',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Stock'),
        ),
    ]
