# Generated by Django 3.2.8 on 2021-10-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_atributesvalue_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atributesvalue',
            name='specification_2',
        ),
    ]
