# Generated by Django 3.2.8 on 2021-10-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20211029_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(blank=True, choices=[('ST', 'Starter'), ('BU', 'Business'), ('AD', 'Advanced')], default='BU', max_length=2, null=True)),
                ('template', models.CharField(blank=True, choices=[('01', 'Limpua sans sidebar'), ('02', 'Limpua avec sidebar'), ('03', 'marchesa'), ('04', 'pmatel'), ('05', 'e-vape city'), ('06', 'molla 1')], default='02', max_length=2, null=True)),
                ('color_1', models.CharField(blank=True, max_length=6, null=True)),
                ('color_2', models.CharField(blank=True, max_length=6, null=True)),
                ('color_3', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
