# Generated by Django 3.2.8 on 2021-10-30 09:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='color_1',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='couleur 1'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='color_2',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='couleur 2'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='color_3',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='couleur 3'),
        ),
    ]
