# Generated by Django 3.2.8 on 2021-10-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20211030_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='mini_about',
            field=models.TextField(blank=True, null=True, verbose_name="Petit texte a propos de l'entreprise ( bas de page)"),
        ),
    ]
