# Generated by Django 3.2.8 on 2021-10-30 10:26

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_mini_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='color_1',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='color_2',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='color_3',
        ),
        migrations.AddField(
            model_name='configuration',
            name='buttons',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='couleur des bouttons'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='links_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='couleur du text liens'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='nav_bar',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='couleur de la bar de navigation'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='text_buttons',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='couleur du text des bouttons'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='text_nav_bar',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='couleur du texte de la bar de navigation'),
        ),
    ]
