# Generated by Django 3.2.8 on 2021-10-30 10:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20211030_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='buttons',
            new_name='buttons_color',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='nav_bar',
            new_name='header_color',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='text_buttons',
            new_name='text_buttons_color',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='text_nav_bar',
            new_name='text_nav_bar_color',
        ),
        migrations.AddField(
            model_name='configuration',
            name='nav_bar_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='couleur de la bar de navigation'),
        ),
    ]
