# Generated by Django 3.2.8 on 2021-11-01 07:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20211030_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='theme_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='couleur du Theme'),
        ),
    ]
