# Generated by Django 3.2.8 on 2021-11-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_configuration_theme_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balise', models.TextField(blank=True, null=True, verbose_name='Script Analytics')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': '10. Balises META',
                'verbose_name_plural': '10.  Balises META',
            },
        ),
    ]
