# Generated by Django 3.2.8 on 2021-11-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='only_home_page',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
    ]
